DATA:
  url: "https://analyticsengineeringprojects.s3.eu-west-1.amazonaws.com/AE_ChessAnalytics.7z"
  save_as: "AE_ChessAnalytics.7z"
  data_dir: "../data/"
  games_dir: data_dir+"Games/"
  players_dir: data_dir +"Players/"
  games_to_csv: data_dir +"games.csv"

DATABASE:
  #user='philippe', password='philippe', host='192.168.0.35', database='Datascientest')
  db_host: 'localhost'
  db_database: 'Datascientest'
  db_user: 'root'
  db_password: 'cuchri_dev'
