DATA:
  url: "https://analyticsengineeringprojects.s3.eu-west-1.amazonaws.com/AE_ChessAnalytics.7z"
  save_as: extract_load/data/AE_ChessAnalytics.7z
  data_dir: extract_load/data
  games_dir: extract_load/data/Games
  players_dir: extract_load/data/Players
  games_to_csv: extract_load/data/games.csv
  db_log : extract_load/db.log
  db_error_log : extract_load/file-error.log

DATABASE:
  db_host: '192.168.0.35'
  db_database: 'chess'
  db_user: 'philippe'
  db_password: 'philippe'


DATA_christophe:
  url: "https://analyticsengineeringprojects.s3.eu-west-1.amazonaws.com/AE_ChessAnalytics.7z"
  save_as: "./data/AE_ChessAnalytics.7z"
  data_dir: "./data/"
  games_dir: "./data/Games/"
  players_dir: "./data/Players/"
  games_to_csv: "./data/games.csv"


DATABASE_christophe:
  db_host: '127.0.0.1'
  db_database: 'Datascientest'
  db_user: 'root'
  db_password: 'Root#1234'


