DATA:
  url: https://analyticsengineeringprojects.s3.eu-west-1.amazonaws.com/AE_ChessAnalytics.7z
  save_as: AE_ChessAnalytics.7z
  data_dir : data
  games_dir: data/Games
  players_dir: data/Players
  db_log : db.log
  db_error_log : file-error.log

#

DATABASE:
  db_host: '192.168.0.35'
  db_database: 'chess7'
  db_user: 'philippe'
  db_password: 'philippe'


