[mysql]
host = "192.168.0.35"
port = 3306
database = "datascientest"
user = "philippe"
password = "philippe"

[mysql_cp]
host = "localhost"
port = 3306
database = "datascientest"
user = "root"
password = "Root#1234"