[theme]
base="dark"


# Primary accent for interactive elements
primaryColor = '#dddddd'

# Background color for the main content area
backgroundColor = '#111111'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#333333'

# Color used for almost all text
textColor = '#cccccc'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"

[deprecation]
showPyplotGlobalUse = false