name: Run tests
on:
  push

env:
  MYSQL_ROOT_PASSWORD: Root#1234

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install packages
        run: |
          python3 -m pip install --upgrade -r requirements.txt
      - name: start mysql
        run: |
          sudo /etc/init.d/mysql start
          sudo apt-get install -y mysql-client libmysqlclient-dev
          mysql alter user 'root'@'localhost' identified with mysql_native_password by 'Root#1234';
          mysql --host 127.0.0.1 -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
      - name: Run tests on pytest
        run: |
          python3 -m pytest